### ISSUE TITLE
Viewer page removed on dev.embedr.eu

### ISSUE THREAD

**Issue by tomkr** [tomkr/embedr#92] opened 2015-11-23 21:57 UTC
I can't seem to access the viewer page on dev.embedr.eu. It was removed from the list of pages, and I recreated it, but this seems to have generated a viewer-2 slug, which doesn't work. Is there something you can do?

**Comment by mzeinstra** [comment] 2015-11-23 22:01
I've restored it from the trash, works now?

**Comment by tomkr** [comment] 2015-11-24 19:16
As we discussed, there seems to be some weird caching going on on the dev server. I don't think this used to be the case. Can you check what is going on?

**Comment by mzeinstra** [comment] 2015-11-26 14:11
Acting as a sys-admin. Closing this issue. Will no fix, is a feature not a bug. 

That's not how the internet works  ;)

**Closed by mzeinstra** 2015-11-26 14:11 UTC
