### ISSUE TITLE
Images overlap when you move from a content page to a new search query

### ISSUE THREAD

**Issue by Taskamp** [tomkr/embedr#42] opened 2015-07-17 11:46 UTC
If you go to a content page (eg. about) there are images on this page as well. If you then do a direct search query from there, and you click on one of the search results, the image 'merges' with the image that is on the content page. 

![screen shot 2015-07-17 at 13 45 38](https://cloud.githubusercontent.com/assets/3542255/8746502/25901542-2c8a-11e5-89cc-e96890f276a2.png)

**Comment by mzeinstra** [comment] 2015-07-17 11:58
This is a duplicate of #33 and #37, closing.

**Closed by mzeinstra** 2015-07-17 11:58 UTC
Labels: bug
